{{- if .Values.huggingface.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.huggingface.tokenSecretName }}
  labels:
    app.kubernetes.io/name: model-provisioner
type: Opaque
data:
  token: {{ .Values.huggingface.token | b64enc | quote }}
{{- end }}